//
// Generated file, do not edit! Created by opp_msgc 4.2 from jobDone.msg.
//

#ifndef _JOBDONE_M_H_
#define _JOBDONE_M_H_

#include <omnetpp.h>

// opp_msgc version check
#define MSGC_VERSION 0x0402
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgc: 'make clean' should help.
#endif



/**
 * Class generated from <tt>jobDone.msg</tt> by opp_msgc.
 * <pre>
 * packet JobDone {
 *     int workerId;
 * }
 * </pre>
 */
class JobDone : public ::cPacket
{
  protected:
    int workerId_var;

  private:
    void copy(const JobDone& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const JobDone&);

  public:
    JobDone(const char *name=NULL, int kind=0);
    JobDone(const JobDone& other);
    virtual ~JobDone();
    JobDone& operator=(const JobDone& other);
    virtual JobDone *dup() const {return new JobDone(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual int getWorkerId() const;
    virtual void setWorkerId(int workerId);
};

inline void doPacking(cCommBuffer *b, JobDone& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, JobDone& obj) {obj.parsimUnpack(b);}


#endif // _JOBDONE_M_H_
